version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: ["sahjanand-mart", "run", "--debug", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"

  # Remove nginx for development